### ISSUE TITLE
How to install ... for Rust-novices?

### ISSUE THREAD

**Issue by benjmin-r** [Ookami86/dokio#2]
As a person with almost no knowledge about Rust and/or cargo, I'm missing information in the README (or somewhere else) on how to install/use dokio. Maybe a link to the right portion of the cargo docs would already suffice?!

Thanks for any pointers!

**Comment by johanneswseitz** [comment]
There's binaries for every platform at https://github.com/Ookami86/dokio/releases - I added the link to the readme.md file :)
